### ISSUE TITLE
Strange behaviour with slow > 1

### ISSUE THREAD

**Issue by kinow** [ianthehenry/bauble#13]
Hi, when I have a torus with `rotate ... | slow 0.25` I notice that it rotates slowly, because of the `slow`, I believe. But when I have `slow > 1`, there is no warning, but the torus behaviour doesn't seem to match with what I expected (a warning, or to actually work as `fast` instead?).

Thanks for Bauble! It's fun! GIF below.

![2024-08-27 20-39-36](https://github.com/user-attachments/assets/d6e46de2-3711-4d7b-8fd7-3283370b0895)

**Comment by ianthehenry** [comment]
Hi! Okay so `slow` is a poorly named function. It doesn't actually slow down *time*, it slows down *space* around the shape. And if you use it with a coefficient greater than one, it speeds up space around your shape, which can cause rays to land inside the shape or miss the shape altogether (the debug view in the top right -- the arrows -- will show you a visualization of how close the rays are to the final shape. Any magenta means that the ray landed inside).

This is... confusing; the tutorial has more info about "slowing space" with some examples of when this makes sense.

There isn't a function right now to implicitly speed up time, but you explicitly rotate faster by scaling `t`. Try this instead:

```janet
(torus :z 100 50
| twist :y 0.00
| rotate :x (t * 2)
| fresnel
)
```

**Comment by ianthehenry** [comment]
(The `slow` is necessary in the default example because `twist` distorts space in a non-linear way, but if you remove the twist then you can remove the slow as well.)

**Comment by kinow** [comment]
>There isn't a function right now to implicitly speed up time, but you explicitly rotate faster by scaling t. Try this instead:

Scaling `t` definitely works, thanks! And thanks for the explanation!

>Hi! Okay so slow is a poorly named function. It doesn't actually slow down time, it slows down space around the shape.

Do you think it'd be possible to have something like a dropdown or link to docs when you hover over functions in bauble.studio? That way `slow` could have a short description similar to what you described above.

Thanks again!

**Comment by kinow** [comment]
>This is... confusing; the tutorial has more info about "slowing space" with some examples of when this makes sense.

Found this searching for slowing space, https://github.com/ianthehenry/bauble/blob/fc0d5f3cd4831d77eae1a2b462edfd9074e29345/studio/examples/intro.janet#L642-L652

In case others read this issue.

>(the debug view in the top right -- the arrows -- will show you a visualization of how close the rays are to the final shape. Any magenta means that the ray landed inside).

Hadn't seen that! That's useful, thanks!

**Comment by kinow** [comment]
I think this can be closed now.

**Comment by ianthehenry** [comment]
> Do you think it'd be possible to have something like a dropdown or link to docs when you hover over functions in bauble.studio? That way slow could have a short description similar to what you described above.

This is a good idea! There is a tooltip that should appear automatically as you type (or if you press ctrl-space) but that's not as discoverable as a hover tooltip if you're looking at existing code.
