### ISSUE TITLE
The code in bauble.studio by default fails on load

### ISSUE THREAD

**Issue by yminsky** [ianthehenry/bauble#4]
I get this error immediately on load:

```
error: (map-color) unexpected vec3 argument (0 1 0)
  in errorf [boot.janet] (tailcall) on line 171, column 3
  in _thunk [script] (tailcall) on line 119, column 17
  in evaluate [bauble-evaluator.janet] on line 73, column 7
```

**Comment by yminsky** [comment]
Ah, the issue is that it remembers old code when I load up by default. This is a little confusing, I guess, for someone who comes back to it for the first time. It would be lovely if there was a simple way of loading the current default code, but it's not a big deal.

**Comment by ianthehenry** [comment]
Yeah, this is really dumb and annoying. The not-very-simple way to load the current tutorial is to clear out the text field and then refresh the page. I should add a reset button...
